### ISSUE TITLE
PyPi release

### ISSUE THREAD

**Issue by shantanugoel** [django-silk/silk#106]
There hasn't been a pypi release for almost 6 months. Is it possible to do so, especially for the django 1.9 compatibility updates?

**Comment by avelis** [comment]
I can definitely see the use case for a maintenance release.

@mford90 thoughts?

**Comment by avelis** [comment]
@shantanugoel At the moment I do not have PyPi release capabilities. In an effort to help out, I have made at least a Github release that could be referenced: https://github.com/django-silk/silk/tree/0.5.7

**Comment by shantanugoel** [comment]
Thanks a lot, @avelis. I'll move to this tag :) Will be good if @mtford90 can make a pypi release as well for wider usage.

**Comment by mtford90** [comment]
I'll do this tomorrow - @avelis I can also look into giving you access to that ;)

**Comment by avelis** [comment]
@mford90 Sweet! I have made some commits to the branch. So you might need to check out a tag and push it to PyPi.

**Comment by mtford90** [comment]
Got it!

**Comment by mtford90** [comment]
Done. @avelis - if you give me your pypi username I can give you the permissions needed to upload new versions

**Comment by avelis** [comment]
@mtford90 Thanks for publishing a release.

My PyPi username is the same as my Github username. :-)

**Comment by mtford90** [comment]
@avelis done - you should now have permissions.

Process for release is as follows:

* Bump version & requirements in `setup.py`
* Execute `python setup.py sdist register upload` to push to pypi

**Comment by avelis** [comment]
@mtford90 Got it!
