### ISSUE TITLE
Using django six rather then maintaining one

### ISSUE THREAD

**Issue by auvipy** [django-silk/silk#112]
is there any reason still to maintain one? @mtford90 @avelis looking for inputs and I will work to update the code to django six if both of you agree

**Comment by avelis** [comment]
@auvipy One reason I think this is this way is to ensure a version of six a the library is using vs being overridden to a different version in a virtualenv.

With that said, if you feel it is easier to move onto a newer version of six I am not against that either.

**Comment by auvipy** [comment]
I will try my proposed changes and send a PR. then lets see

**Comment by hanleyhansen** [comment]
The old six should be completely removed now. The last remnants were taken care of in my pr: https://github.com/django-silk/silk/pull/122
