### ISSUE TITLE
Select a path to save profiling files

### ISSUE THREAD

**Issue by javaguirre** [django-silk/silk#131]
It would be nice to have a constant to set the path of the `prof` files.

**Comment by avelis** [comment]
@javaguirre I believe I understand the feature request. Could you describe your use case a little bit more for better context?

**Comment by javaguirre** [comment]
I want to be able to have the `*.prof` in certain path I choose, not in the root of my project.
<img width="1093" alt="screen shot 2016-07-21 at 16 15 59" src="https://cloud.githubusercontent.com/assets/488556/17025927/7240b7b4-4f5e-11e6-90d0-71065245dd58.png">

**Comment by javaguirre** [comment]
I'd like to do it. :-)

**Comment by avelis** [comment]
@javaguirre if you can make a pr for it. I can take a look and merge it in if it checks out

**Comment by avelis** [comment]
@javaguirre I merged your PR in. Thanks for making your contribution for this issue.

**Comment by javaguirre** [comment]
Thank you @avelis more to come I hope! :-)

**Comment by avelis** [comment]
@javaguirre It's in master now. I have added a snippet to the README on how it's used. I will make a release soon. Likely by EOB Friday.
