### ISSUE TITLE
Pypi version upload

### ISSUE THREAD

**Issue by hanleyhansen** [django-silk/silk#141]
Hi @avelis,

Would you mind uploading a new version to pypi (0.7.1) so that my PR changes make it into the package? Please and thank you!

**Comment by avelis** [comment]
@hanleyhansen Ok. Should be on pypi. And the release is under the releases tab a v0.7.1

**Comment by hanleyhansen** [comment]
Confirmed! Awesome! Thanks! Closing this issue.
