### ISSUE TITLE
Bad requirements for postgres based installations

### ISSUE THREAD

**Issue by hassonofer** [django-silk/silk#142]
After merging #140, `pip install django-silk` fails for postgres based installations.

mysqlclient was added as a requirement, which produces the following error (if no mysql installation exist).

``` shell
Collecting mysqlclient (from django-silk)
  Using cached mysqlclient-1.3.9.tar.gz
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-KYR3WJ/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 44, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 26, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```

**Comment by avelis** [comment]
@hassonofer I had a feeling this was going to happen. For now install version `1.7.0`. I will have to figure out an SQL agnostic solution for what @hanleyhanson was looking for in the last release.

**Comment by hassonofer** [comment]
First of all, thank you very much for the prompt response.

I did not test it myself, but as far as I know ```django.db.DatabaseError``` or the more general ```django.db.Error``` should catch this error.
As documented here: https://github.com/django/django/blob/149ace94dfc10504a0e69462c7737f5ce05340a4/docs/releases/1.4.txt#L880

**Comment by hanleyhansen** [comment]
Hi @hassonofer,

I'll be home on 30 mins and will try that. It if works I'll put another PR up. I'm sore @avelis will merge it right away so we don't hold you up. 

Sorry for the inconvenience.

**Comment by hassonofer** [comment]
There is not rush at all, I updated my puppet manifests today to stay on 0.7.0 :)

**Comment by avelis** [comment]
@hassonofer Thanks for suggesting a `django.db.DatabaseError` error catch instead. Sounds like the right type of error to catch. @hanleyhansen If you get a PR working I will promptly merge as well.

I will also into taking down 1.7.1 from PyPi to avoid others from getting caught into this issue.

**Comment by avelis** [comment]
@hanleyhansen I made a [branch](https://github.com/django-silk/silk/tree/database-error-try-catch) to try out a different class in the exception catching. Can you confirm/deny if that works for you?

**Comment by avelis** [comment]
Fixed in release https://github.com/django-silk/silk/releases/tag/0.7.2

**Comment by hassonofer** [comment]
I forgot to update here, it works great, thanks for everyone who helped.
