### ISSUE TITLE
No Silk profiling was performed for this request. Use the silk_profile decorator/context manager to do so.

### ISSUE THREAD

**Issue by danmash** [django-silk/silk#147]
Hi, I'm trying to profile django app and can't get any silk profiling.
I followed all your instructions from "installation" docs section.
I added @silk_profile decarators and silk_profile contexts, but page `silk/profiling/` is still empty

**Comment by avelis** [comment]
@danmash Can you share a little more on your setup? Which request oriented views are you decorating?

**Comment by lockie** [comment]
@danmash Most probably you've forgotten the `SILKY_PYTHON_PROFILER = True` setting.

**Comment by fwip** [comment]
I was experiencing this issue earlier. For me, it was because I was using the new `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES` and didn't notice the difference when looking over the README. 
I fixed the issue by installing the latest from master, instead of the most recent release.

**Comment by avelis** [comment]
@fwip Is this issue resolved? If so I am going to close it.

If you feel the docs could use an improvement help I encourage a PR.

**Comment by fwip** [comment]
Yes, my issue was resolved in a recent release. Thank you!
