### ISSUE TITLE
Difficult to install on windows: Needs wheels.

### ISSUE THREAD

**Issue by kingllama** [django-silk/silk#149]
I'd love to use silk but it's next to impossible to install it on windows. [Wheels](http://pythonwheels.com/) is the new standard for python packages (it replaces eggs) and would help with windows installation.

**Comment by avelis** [comment]
@kingllama Thanks for the suggestion. I didn't know Window's installations were troublesome.

**Comment by auvipy** [comment]
I have updated several packages to use wheel so I hope I can make the change.

**Comment by auvipy** [comment]
@avelis https://github.com/django-silk/silk/pull/168 this should fix the issues

**Comment by avelis** [comment]
@kingllama Release 1.0.0 was released with a published wheel. I hope this helps alleviate your windows installation woes.
