### ISSUE TITLE
When installing silk asking for mysql library. But I'm using postgresql.

### ISSUE THREAD

**Issue by miratcan** [django-silk/silk#150]
Am I trying to install wrong package or is there something wrong about that dependency?

**Comment by avelis** [comment]
@miratcan This was an issue with the last release. It's fixed on master. Either downgrade to 0.7.0 to the release or pull form master. Sorry for any inconvenience.

**Comment by avelis** [comment]
Fixed in release https://github.com/django-silk/silk/releases/tag/0.7.2

**Comment by miratcan** [comment]
But pip install gave me this error. May be PyPi package must be renewed.
