### ISSUE TITLE
Profiling files get copied into MEDIA_ROOT

### ISSUE THREAD

**Issue by r3m0t** [django-silk/silk#151]
Silk saves prof files to `SILKY_PYTHON_PROFILER_RESULT_PATH` but then copies them all into `MEDIA_ROOT`.

The solution is to specify the `storage=` on the FileField as an instance of this:

```python
class SilkyStorage(FileSystemStorage):
    def __init__(self, **kwargs):
        kwargs['location'] = settings.SILKY_PYTHON_PROFILER_RESULT_PATH
        super(SilkyStorage, self).__init__(**kwargs)
```

Also, it isn't clear from the documentation what SILKY_PYTHON_PROFILER_RESULT_PATH is meant to be relative to.

I'm running 0.7.0 due to the PostgreSQL issues in 0.7.1.

**Comment by avelis** [comment]
@r3m0t I will get a release for this issue addressed soon.

**Comment by xyb** [comment]
@avelis is it time to release a new version? I'm looking forward to use this great patch. Thank you.

**Comment by avelis** [comment]
@xyb release made
