### ISSUE TITLE
Query time-outs

### ISSUE THREAD

**Issue by jacksonofalltrades** [django-silk/silk#158]
After the amount of data collected is larger than a certain size (not exactly sure what that size is), the silk admin page stops responding and in fact eventually just gets an empty response. I've spent a lot of time trying to figure out how this is possible, and the best I can come up with is that some of the aggregate queries take way too long to return.

Our best strategy at this point is to manually edit the queries and make them less time-consuming. Any other suggestions?

**Comment by avelis** [comment]
@jacksonofalltrades Depending on your request volume, a little bit of tuning can go a long way. I suggest either lowering the `SILKY_INTERCEPT_PERCENT` value to some number below 50 (perhaps 25). You could also use the `SILKY_INTERCEPT_FUNC` that can determine which requests to log.

**Comment by avelis** [comment]
@jacksonofalltrades In other avenues if you find enhancements to performance of certain aggregations I can always open to PR's.

**Comment by jacksonofalltrades** [comment]
Great, thank you for your quick response, we can try those!

So just to clarify, is the reason for those two configs precisely because capturing everything is an issue for others as well? That would make me feel better :)

**Comment by avelis** [comment]
@jacksonofalltrades It's hard to say for sure, I would have to search through the repo's history. However, having granular control to determine what to collect and at what percentage is helpful in this scenario.

Rest easy @jacksonofalltrades you are likely not alone. :-)

**Comment by avelis** [comment]
@jacksonofalltrades If the above suggestions work for you, I am going to close this issue.
