### ISSUE TITLE
Middleware setting in Django 1.10

### ISSUE THREAD

**Issue by ukjin1192** [django-silk/silk#159]
Django >= 1.10 : `MIDDLEWARE` is list type.
Django < 1.9 : `MIDDLEWARE_CLASSES` is tuple type.

Details here : https://docs.djangoproject.com/en/1.10/releases/1.10/#new-style-middleware

Therefore,

~~~~
MIDDLEWARE_CLASSES = (
    ...
    'silk.middleware.SilkyMiddleware',
    ...
)
~~~~

would be

~~~~
MIDDLEWARE = [
    ...
    'silk.middleware.SilkyMiddleware',
    ...
]
~~~~

**Comment by avelis** [comment]
@ukjin1192 If you would like to update the README with a PR I can happily merge it. I believe there are still users that are on versions that would require listing both styles.

**Comment by avelis** [comment]
@ukjin1192 Thanks again for the PR!!!
