### ISSUE TITLE
Silk shows 0 time for all requests?

### ISSUE THREAD

**Issue by svvitale** [django-silk/silk#161]
I'm just trying silk for the first time and it looks awesome!  After adding the app and the middleware, and running the migrations, I'm seeing requests being logged, but I'm not seeing any time recorded.

![2017-02-18 09_19_39-silky](https://cloud.githubusercontent.com/assets/137162/23094717/636e5d14-f5bb-11e6-8e7a-ccb0cf89a863.png)

I must be missing something.  Any idea?

**Comment by avelis** [comment]
@svvitale That looks bizarre, can you give some more info into your setup?

**Comment by chessbr** [comment]
+1 installed here the last version and as installation tutorial says..

**Comment by chessbr** [comment]
Installed 0.7.2 and now it works!

**Comment by svvitale** [comment]
My setup is Python 3.5.1, Postgres 9.5.2 with the following packages installed:

```
autopep8==1.2.4
dj-database-url==0.4.0
dj-static==0.0.6
Django==1.9.4
django-silk==0.7.3
django-sslserver==0.19
django-toolbelt==0.0.1
et-xmlfile==1.0.1
gunicorn==19.4.5
jdcal==1.3
Jinja2==2.9.5
MarkupSafe==0.23
openpyxl==2.4.1
pep8==1.7.0
psycopg2==2.6.2
Pygments==2.2.0
python-dateutil==2.5.1
python-http-client==2.2.1
pytz==2016.10
requests==2.9.1
rollbar==0.11.5
sendgrid==3.6.3
six==1.10.0
smtpapi==0.3.1
sqlparse==0.2.2
static3==0.6.1
```

Same result as @chessbr, if I roll back to 0.7.2, all is well.

**Comment by utkbansal** [comment]
Facing the same issue. Silk looks something like this -
<img width="867" alt="screen shot 2017-03-02 at 9 19 47 pm" src="https://cloud.githubusercontent.com/assets/8345336/23514690/14598b36-ff8e-11e6-8a4a-c2ac9ae23f8a.png">

Middleware is as follows-
```

MIDDLEWARE_CLASSES = [
    'silk.middleware.SilkyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'silk.middleware.SilkyMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'direct_me.disable.DisableCSRF',
]

```

Django==1.10.4 with Postgres.

**Comment by svvitale** [comment]
Works great, thanks!

**Comment by unformatt** [comment]
I started having this same problem, nothing changed in my setup AFAIK. Using django 1.9.5. I upgraded to silky 1.0.0 hoping it would fix the problem. 

in my settings
```python
SILKY_ENABLED = True
if SILKY_ENABLED:
    SILKY_PYTHON_PROFILER = True
    SILKY_PYTHON_PROFILER_BINARY = False
    INSTALLED_APPS.append('silk')
    MIDDLEWARE_CLASSES.insert(0, 'silk.middleware.SilkyMiddleware')
```

![image](https://cloud.githubusercontent.com/assets/157132/25761003/3a1696c0-31a7-11e7-92aa-abc0d5e65db9.png)
