### ISSUE TITLE
Use redis for backend

### ISSUE THREAD

**Issue by rmad17** [django-silk/silk#163]
Can't we store the data in redis. I dont want hits on my db from silk code. Is that possible?

**Comment by avelis** [comment]
There is no direct support to use Redis as a backend. Solutions to use Redis could be using CacheOps to cache access to a redis instance but still uses the DB.

Another solution could be to listen to pre_save signals of the model to also store the data to a redis instance and block the actual save. However, I couldn't guarantee it would work.

You could also try the [multi-db configuration](https://docs.djangoproject.com/en/dev/topics/db/multi-db/) With a custom router and store the Silk data in a db not connected to your main datastore.

Many options that don't involve directly changing this library which I hope can help.
