### ISSUE TITLE
Consider moving project to jazzband

### ISSUE THREAD

**Issue by albertyw** [django-silk/silk#184]
I noticed that you're looking for contributors, according to your README.  Would you be interested in moving the project to [jazzband](https://jazzband.co/about/guidelines)?

**Comment by avelis** [comment]
I am open to it!

**Comment by avelis** [comment]
@albertyw what benefits does moving it to jazzband do?

**Comment by mtford90** [comment]
Also open to it. Have no objections to breathing more life into the repo.

@albertyw what's the process? Will current contributors have their access to the repo maintained?

**Comment by albertyw** [comment]
The main person to contact about jazzband is probably @jezdez.  

You still maintain access to the repo by joining the jazzband project through their website, which also contains the [guidelines for adding a new repository](https://jazzband.co/about/guidelines).
