### ISSUE TITLE
Build fails occasionally due to "missing manage.py"

### ISSUE THREAD

**Issue by mtford90** [django-silk/silk#32]
The test for permissions when viewing files in the SQL traceback occasionally fails.

**Comment by auvipy** [comment]
sorry for poking but is this issue still exist? @avelis I am trying to have comprehensive idea about the present status of the project so that I can contribute better. busy with maintaining other projects though

**Comment by avelis** [comment]
@auvipy I would imagine that can does under certain conditions but I am not sure how to test for them. Since I have not seen this appear on TravisCI I will close this.

**Comment by auvipy** [comment]
I do also believe this doesn't exist now. if so then this could be re-opened later
