### ISSUE TITLE
TemplateSyntaxError at /silk/ Invalid filter: 'silk_date_time'

### ISSUE THREAD

**Issue by Alkalit** [django-silk/silk#82]
I have fresh installation of silk, but I am getting the error when try switch to /silk/. The most likely cause for this is because in our project we already using tags located in file named filters.py so it raises name conflict with silk tags. Of course we can rename it, or set into nested package, but I think it would be nice if silk will use more specific names for tag files to avoid such errors in future.

**Comment by avelis** [comment]
This issue was resolved in commit: ce50e972971b06bdc2f0983d73059054388573c8
