### ISSUE TITLE
Unittesting

### ISSUE THREAD

**Issue by Alkalit** [django-silk/silk#87]
How about to write some tests for this app?

**Comment by avelis** [comment]
@Alkalit First, I appreciate you expressing interest in making a contribution. You can never have to many tests I always say.

We currently have about 110 tests passing thus far.

If you make a pull request with any tests you write I can be happy to take a look and pull them into the master branch.

**Comment by Alkalit** [comment]
@avelis Deal.

**Comment by avelis** [comment]
Addressed in pull request: #93
