### ISSUE TITLE
base64 encoded responses break unit tests for Python3

### ISSUE THREAD

**Issue by avelis** [django-silk/silk#98]
Visible under the last build run on TravisCI(https://travis-ci.org/django-silk/silk/jobs/103436926), the enhancement merged #94 isn't quite Python3 compliant.

This has to due with base64 encoder expecting a byte string and not a string.

Potential solution for https://github.com/django-silk/silk/blob/master/silk/model_factory.py#L240:
```python
# Python3 requires a byte-sting
if isinstance(content, str):
    content = content.encode('utf-8')
silky_response.raw_body = base64.b64encode(content)
```

**Comment by avelis** [comment]
@trik I know you worked on #94 for issues #85 & #1. Would you mind weighing in on if my potential solution (above) will still keep your enhancement intact?

I want to be certain before I unintentionally break the core part of the feature.

**Comment by trik** [comment]
@avelis sorry, i never use python3.. i made some tests and everything seems fine with your patch, requests are correctly decoded also in p3
anyway, in model_factory.py lines 240-244, i would have done:

```python
try
    silky_response.raw_body = base64.b64encode(content)
except TypeError:
    silky_response.raw_body = base64.b64encode(content.encode('utf-8'))
```

**Comment by avelis** [comment]
@trik Thanks for your input and suggestions! This will help me move forward with some confidence.
